# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Distribute App to TestFlight"
  lane :beta do

    app_store_connect_api_key(
      key_id: "973W48LM6J",
      issuer_id: "4ebef045-a694-4204-a8c7-da05ae3b544f",
      key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghI3nSVW5Ag4NgOs9\nFamSqiayJ+dxSONWTqNCql5bnLqgCgYIKoZIzj0DAQehRANCAATezW5D2aK4hZ9M\ngGhckNrcePOnmdXaa5qzNdOjWWqHbG9oghdmYDgf7m//tfCt8kDSVfGTlaG4pXTY\n8ZzNgcxa\n-----END PRIVATE KEY-----",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    isCI = is_ci

    if isCI

      create_keychain(
        name: "match_keychain",
        password: "",
        default_keychain: true,
        timeout: 21600,
        unlock: true,
        lock_when_sleeps: false
      )

      match(
        type: "appstore",
        app_identifier: "com.cheffi.cheffi",
        keychain_name: "match_keychain",
        keychain_password: ""
      )

    else

      match(
        type: "appstore",
        app_identifier: "com.cheffi.cheffi"
      )

    end

    build_app(
      workspace: "Cheffi.xcworkspace",
      configuration: "Release",
      scheme: "Cheffi",
      silent: true,
      clean: true,
      include_bitcode: false,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.cheffi.cheffi" => "match AppStore com.cheffi.cheffi"
        },
        teamID: "A9F8XLHP2Y"
      }
    )

    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: false,
      distribute_external: false,
      groups: [ "Cheffi_Internal_Tester_Group" ]
    )

  end
end
