# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Distribute App to TestFlight"
  lane :beta do

    ENV["BUILD_NUMBER"] = Time.new.strftime("%Y%m%d%H%M%S")

    increment_build_number(
      build_number: ENV["BUILD_NUMBER"],
      xcodeproj: "Cheffi.xcodeproj"
    )

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    isCI = is_ci

    if isCI

      create_keychain(
        name: "match_keychain",
        password: "",
        default_keychain: true,
        timeout: 21600,
        unlock: true,
        lock_when_sleeps: false
      )

      match(
        type: "appstore",
        app_identifier: "com.cheffi.cheffi",
        keychain_name: "match_keychain",
        keychain_password: ""
      )

    else

      match(
        type: "appstore",
        app_identifier: "com.cheffi.cheffi"
      )

    end

    build_app(
      workspace: "Cheffi.xcworkspace",
      configuration: "Release",
      scheme: "Cheffi",
      silent: false,
      clean: true,
      include_bitcode: false,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.cheffi.cheffi" => "match AppStore com.cheffi.cheffi"
        },
        teamID: "A9F8XLHP2Y",
        signingStyle: "manual"
      }
    )

    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: false,
      distribute_external: false,
      groups: [ "Cheffi_Internal_Tester_Group" ]
    )

  end
end
