name: 'Auto Assign Issue'
on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Assign issue to creator
      run: |
        curl \
        -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
        -d '{"assignees": ["${{ github.event.issue.user.login }}"]}'
